import type { MenuCategory } from "../types/MenuItem";

export const getMenu = (t: (key: string) => string): MenuCategory[] => [
  {
    category: t("common.menu.nigiri.title"),
    items: [
      {
        id: 1,
        price: 22,
        image: "/images/menu/1.webp",
        name: t("common.menu.nigiri.items.1.name"),
        description: t("common.menu.nigiri.items.1.description"),
        count: t("common.menu.nigiri.items.1.count"),
      },
      {
        id: 2,
        price: 24,
        image: "/images/menu/2.webp",
        name: t("common.menu.nigiri.items.2.name"),
        description: t("common.menu.nigiri.items.2.description"),
        count: t("common.menu.nigiri.items.2.count"),
      },
      {
        id: 3,
        price: 24,
        image: "/images/menu/3.webp",
        name: t("common.menu.nigiri.items.3.name"),
        description: t("common.menu.nigiri.items.3.description"),
        count: t("common.menu.nigiri.items.3.count"),
      },
      {
        id: 4,
        price: 23,
        image: "/images/menu/4.webp",
        name: t("common.menu.nigiri.items.4.name"),
        description: t("common.menu.nigiri.items.4.description"),
        count: t("common.menu.nigiri.items.4.count"),
      },
      {
        id: 5,
        price: 22,
        image: "/images/menu/5.webp",
        name: t("common.menu.nigiri.items.5.name"),
        description: t("common.menu.nigiri.items.5.description"),
        count: t("common.menu.nigiri.items.5.count"),
      },
    ],
  },

  {
    category: t("common.menu.gunkan.title"),
    items: [
      {
        id: 6,
        price: 24,
        image: "/images/menu/6.webp",
        name: t("common.menu.gunkan.items.1.name"),
        description: t("common.menu.gunkan.items.1.description"),
        count: t("common.menu.gunkan.items.1.count"),
      },
      {
        id: 7,
        price: 22,
        image: "/images/menu/7.webp",
        name: t("common.menu.gunkan.items.1.name"),
        description: t("common.menu.gunkan.items.1.description"),
        count: t("common.menu.gunkan.items.1.count"),
      },
    ],
  },
  {
    category: t("common.menu.makiRoll.title"),
    items: [
      {
        id: 8,
        price: 15,
        image: "/images/menu/8.webp",
        name: t("common.menu.makiRoll.items.1.name"),
        description: t("common.menu.makiRoll.items.1.description"),
        count: t("common.menu.makiRoll.items.1.count"),
      },
      {
        id: 9,
        price: 17,
        image: "/images/menu/9.webp",
        name: t("common.menu.makiRoll.items.2.name"),
        description: t("common.menu.makiRoll.items.2.description"),
        count: t("common.menu.makiRoll.items.2.count"),
      },
      {
        id: 10,
        price: 16,
        image: "/images/menu/10.webp",
        name: t("common.menu.makiRoll.items.3.name"),
        description: t("common.menu.makiRoll.items.3.description"),
        count: t("common.menu.makiRoll.items.3.count"),
      },
      {
        id: 11,
        price: 24,
        image: "/images/menu/11.webp",
        name: t("common.menu.makiRoll.items.4.name"),
        description: t("common.menu.makiRoll.items.4.description"),
        count: t("common.menu.makiRoll.items.4.count"),
      },
      {
        id: 12,
        price: 26,
        image: "/images/menu/12.webp",
        name: t("common.menu.makiRoll.items.5.name"),
        description: t("common.menu.makiRoll.items.5.description"),
        count: t("common.menu.makiRoll.items.5.count"),
      },
      {
        id: 13,
        price: 24,
        image: "/images/menu/13.webp",
        name: t("common.menu.makiRoll.items.6.name"),
        description: t("common.menu.makiRoll.items.6.description"),
        count: t("common.menu.makiRoll.items.6.count"),
      },
      {
        id: 14,
        price: 25,
        image: "/images/menu/14.webp",
        name: t("common.menu.makiRoll.items.7.name"),
        description: t("common.menu.makiRoll.items.7.description"),
        count: t("common.menu.makiRoll.items.7.count"),
      },
      {
        id: 15,
        price: 25,
        image: "/images/menu/15.webp",
        name: t("common.menu.makiRoll.items.8.name"),
        description: t("common.menu.makiRoll.items.8.description"),
        count: t("common.menu.makiRoll.items.8.count"),
      },
      {
        id: 16,
        price: 25,
        image: "/images/menu/16.webp",
        name: t("common.menu.makiRoll.items.9.name"),
        description: t("common.menu.makiRoll.items.9.description"),
        count: t("common.menu.makiRoll.items.9.count"),
      },
    ],
  },
  {
    category: t("common.menu.kaliforniaRoll.title"),
    items: [
      {
        id: 17,
        price: 37,
        image: "/images/menu/17.webp",
        name: t("common.menu.kaliforniaRoll.items.1.name"),
        description: t("common.menu.kaliforniaRoll.items.1.description"),
        count: t("common.menu.kaliforniaRoll.items.1.count"),
      },
      {
        id: 18,
        price: 38,
        image: "/images/menu/18.webp",
        name: t("common.menu.kaliforniaRoll.items.2.name"),
        description: t("common.menu.kaliforniaRoll.items.2.description"),
        count: t("common.menu.kaliforniaRoll.items.2.count"),
      },
      {
        id: 19,
        price: 38,
        image: "/images/menu/19.webp",
        name: t("common.menu.kaliforniaRoll.items.3.name"),
        description: t("common.menu.kaliforniaRoll.items.3.description"),
        count: t("common.menu.kaliforniaRoll.items.3.count"),
      },
      {
        id: 20,
        price: 36,
        image: "/images/menu/20.webp",
        name: t("common.menu.kaliforniaRoll.items.4.name"),
        description: t("common.menu.kaliforniaRoll.items.4.description"),
        count: t("common.menu.kaliforniaRoll.items.4.count"),
      },
    ],
  },
  {
    category: t("common.menu.smok.title"),
    items: [
      {
        id: 21,
        price: 48,
        image: "/images/menu/21.webp",
        name: t("common.menu.smok.items.1.name"),
        description: t("common.menu.smok.items.1.description"),
        count: t("common.menu.smok.items.1.count"),
      },
      {
        id: 22,
        price: 46,
        image: "/images/menu/22.webp",
        name: t("common.menu.smok.items.2.name"),
        description: t("common.menu.smok.items.2.description"),
        count: t("common.menu.smok.items.2.count"),
      },
      {
        id: 23,
        price: 48,
        image: "/images/menu/23.webp",
        name: t("common.menu.smok.items.3.name"),
        description: t("common.menu.smok.items.3.description"),
        count: t("common.menu.smok.items.3.count"),
      },
      {
        id: 24,
        price: 45,
        image: "/images/menu/24.webp",
        name: t("common.menu.smok.items.4.name"),
        description: t("common.menu.smok.items.4.description"),
        count: t("common.menu.smok.items.4.count"),
      },
      {
        id: 25,
        price: 47,
        image: "/images/menu/25.webp",
        name: t("common.menu.smok.items.5.name"),
        description: t("common.menu.smok.items.5.description"),
        count: t("common.menu.smok.items.5.count"),
      },
    ],
  },

  {
    category: t("common.menu.futomaki.title"),
    items: [
      {
        id: 26,
        price: 35,
        image: "/images/menu/empty.svg",
        name: t("common.menu.futomaki.items.1.name"),
        description: t("common.menu.futomaki.items.1.description"),
        count: t("common.menu.futomaki.items.1.count"),
      },
      {
        id: 27,
        price: 38,
        image: "/images/menu/empty.svg",
        name: t("common.menu.futomaki.items.2.name"),
        description: t("common.menu.futomaki.items.2.description"),
        count: t("common.menu.futomaki.items.2.count"),
      },
    ],
  },

  {
    category: t("common.menu.krancz.title"),
    items: [
      {
        id: 28,
        price: 36,
        image: "/images/menu/28.webp",
        name: t("common.menu.krancz.items.1.name"),
        description: t("common.menu.krancz.items.1.description"),
        count: t("common.menu.krancz.items.1.count"),
      },
      {
        id: 29,
        price: 33,
        image: "/images/menu/29.webp",
        name: t("common.menu.krancz.items.2.name"),
        description: t("common.menu.krancz.items.2.description"),
        count: t("common.menu.krancz.items.2.count"),
      },
    ],
  },

  {
    category: t("common.menu.filadelfia.title"),
    items: [
      {
        id: 30,
        price: 37,
        image: "/images/menu/30.webp",
        name: t("common.menu.filadelfia.items.1.name"),
        description: t("common.menu.filadelfia.items.1.description"),
        count: t("common.menu.filadelfia.items.1.count"),
      },
      {
        id: 31,
        price: 39,
        image: "/images/menu/31.webp",
        name: t("common.menu.filadelfia.items.2.name"),
        description: t("common.menu.filadelfia.items.2.description"),
        count: t("common.menu.filadelfia.items.2.count"),
      },
      {
        id: 32,
        price: 44,
        image: "/images/menu/32.webp",
        name: t("common.menu.filadelfia.items.3.name"),
        description: t("common.menu.filadelfia.items.3.description"),
        count: t("common.menu.filadelfia.items.3.count"),
      },
      {
        id: 33,
        price: 44,
        image: "/images/menu/33.webp",
        name: t("common.menu.filadelfia.items.4.name"),
        description: t("common.menu.filadelfia.items.4.description"),
        count: t("common.menu.filadelfia.items.4.count"),
      },
      {
        id: 34,
        price: 44,
        image: "/images/menu/34.webp",
        name: t("common.menu.filadelfia.items.5.name"),
        description: t("common.menu.filadelfia.items.5.description"),
        count: t("common.menu.filadelfia.items.5.count"),
      },
      {
        id: 35,
        price: 38,
        image: "/images/menu/35.webp",
        name: t("common.menu.filadelfia.items.6.name"),
        description: t("common.menu.filadelfia.items.6.description"),
        count: t("common.menu.filadelfia.items.6.count"),
      },
      {
        id: 36,
        price: 43,
        image: "/images/menu/36.webp",
        name: t("common.menu.filadelfia.items.7.name"),
        description: t("common.menu.filadelfia.items.7.description"),
        count: t("common.menu.filadelfia.items.7.count"),
      },
    ],
  },

  {
    category: t("common.menu.smażonyRoll.title"),
    items: [
      {
        id: 37,
        price: 40,
        image: "/images/menu/empty.svg",
        name: t("common.menu.smażonyRoll.items.1.name"),
        description: t("common.menu.smażonyRoll.items.1.description"),
        count: t("common.menu.smażonyRoll.items.1.count"),
      },
      {
        id: 38,
        price: 37,
        image: "/images/menu/empty.svg",
        name: t("common.menu.smażonyRoll.items.1.name"),
        description: t("common.menu.smażonyRoll.items.1.description"),
        count: t("common.menu.smażonyRoll.items.1.count"),
      },
    ],
  },

  {
    category: t("common.menu.pieczonyRoll.title"),
    items: [
      {
        id: 39,
        price: 40,
        image: "/images/menu/empty.svg",
        name: t("common.menu.pieczonyRoll.items.1.name"),
        description: t("common.menu.pieczonyRoll.items.1.description"),
        count: t("common.menu.pieczonyRoll.items.1.count"),
      },
      {
        id: 40,
        price: 41,
        image: "/images/menu/40.webp",
        name: t("common.menu.pieczonyRoll.items.2.name"),
        description: t("common.menu.pieczonyRoll.items.2.description"),
        count: t("common.menu.pieczonyRoll.items.2.count"),
      },
      {
        id: 41,
        price: 43,
        image: "/images/menu/empty.svg",
        name: t("common.menu.pieczonyRoll.items.3.name"),
        description: t("common.menu.pieczonyRoll.items.3.description"),
        count: t("common.menu.pieczonyRoll.items.3.count"),
      },
    ],
  },

  {
    category: t("common.menu.salatka.title"),
    items: [
      {
        id: 42,
        price: 15,
        image: "/images/menu/empty.svg",
        name: t("common.menu.salatka.items.1.name"),
        description: t("common.menu.salatka.items.1.description"),
      },
    ],
  },

  {
    category: t("common.menu.przekąski.title"),
    items: [
      {
        id: 43,
        price: 42,
        image: "/images/menu/43.webp",
        name: t("common.menu.przekąski.items.1.name"),
        description: t("common.menu.przekąski.items.1.description"),
        count: t("common.menu.przekąski.items.1.count"),
      },
    ],
  },

  {
    category: t("common.menu.zupy.title"),
    items: [
      {
        id: 44,
        price: 20,
        image: "/images/menu/empty.svg",
        name: t("common.menu.zupy.items.1.name"),
        description: t("common.menu.zupy.items.1.description"),
        count: t("common.menu.zupy.items.1.count"),
      },
      {
        id: 45,
        price: 25,
        image: "/images/menu/45.webp",
        name: t("common.menu.zupy.items.2.name"),
        description: t("common.menu.zupy.items.2.description"),
        count: t("common.menu.zupy.items.2.count"),
      },
    ],
  },

  {
    category: t("common.menu.ryz.title"),
    items: [
      {
        id: 46,
        price: 25,
        image: "/images/menu/empty.svg",
        name: t("common.menu.ryz.items.1.name"),
        description: t("common.menu.ryz.items.1.description"),
        count: t("common.menu.ryz.items.1.count"),
      },
      {
        id: 47,
        price: 30,
        image: "/images/menu/empty.svg",
        name: t("common.menu.ryz.items.2.name"),
        description: t("common.menu.ryz.items.2.description"),
        count: t("common.menu.ryz.items.2.count"),
      },
      {
        id: 48,
        price: 32,
        image: "/images/menu/empty.svg",
        name: t("common.menu.ryz.items.3.name"),
        description: t("common.menu.ryz.items.3.description"),
        count: t("common.menu.ryz.items.3.count"),
      },
    ],
  },

  {
    category: t("common.menu.zestawy.title"),
    items: [
      {
        id: 49,
        price: 260,
        image: "/images/menu/empty.svg",
        name: t("common.menu.zestawy.items.1.name"),
        description: t("common.menu.zestawy.items.1.description"),
        count: t("common.menu.zestawy.items.1.count"),
      },
      {
        id: 50,
        price: 125,
        image: "/images/menu/empty.svg",
        name: t("common.menu.zestawy.items.2.name"),
        description: t("common.menu.zestawy.items.2.description"),
        count: t("common.menu.zestawy.items.2.count"),
      },
      {
        id: 51,
        price: 150,
        image: "/images/menu/empty.svg",
        name: t("common.menu.zestawy.items.3.name"),
        description: t("common.menu.zestawy.items.3.description"),
        count: t("common.menu.zestawy.items.3.count"),
      },
      {
        id: 52,
        price: 145,
        image: "/images/menu/empty.svg",
        name: t("common.menu.zestawy.items.4.name"),
        description: t("common.menu.zestawy.items.4.description"),
        count: t("common.menu.zestawy.items.4.count"),
      },
      {
        id: 53,
        price: 109,
        image: "/images/menu/53.webp",
        name: t("common.menu.zestawy.items.5.name"),
        description: t("common.menu.zestawy.items.5.description"),
        count: t("common.menu.zestawy.items.5.count"),
      },
      {
        id: 54,
        price: 150,
        image: "/images/menu/empty.svg",
        name: t("common.menu.zestawy.items.6.name"),
        description: t("common.menu.zestawy.items.6.description"),
        count: t("common.menu.zestawy.items.6.count"),
      },
    ],
  },
  {
    category: t("common.menu.dodatki.title"),
    items: [
      {
        id: 55,
        price: 5,
        image: "/images/menu/empty.svg",
        name: t("common.menu.dodatki.items.1.name"),
        description: t("common.menu.dodatki.items.1.description"),
        count: t("common.menu.dodatki.items.1.count"),
      },
      {
        id: 56,
        price: 5,
        image: "/images/menu/empty.svg",
        name: t("common.menu.dodatki.items.2.name"),
        description: t("common.menu.dodatki.items.2.description"),
        count: t("common.menu.dodatki.items.2.count"),
      },
      {
        id: 57,
        price: 5,
        image: "/images/menu/empty.svg",
        name: t("common.menu.dodatki.items.3.name"),
        description: t("common.menu.dodatki.items.3.description"),
        count: t("common.menu.dodatki.items.3.count"),
      },
      {
        id: 58,
        price: 5,
        image: "/images/menu/empty.svg",
        name: t("common.menu.dodatki.items.4.name"),
        description: t("common.menu.dodatki.items.4.description"),
        count: t("common.menu.dodatki.items.4.count"),
      },
      {
        id: 59,
        price: 5,
        image: "/images/menu/empty.svg",
        name: t("common.menu.dodatki.items.5.name"),
        description: t("common.menu.dodatki.items.5.description"),
        count: t("common.menu.dodatki.items.5.count"),
      },
      {
        id: 60,
        price: 5,
        image: "/images/menu/empty.svg",
        name: t("common.menu.dodatki.items.6.name"),
        description: t("common.menu.dodatki.items.6.description"),
        count: t("common.menu.dodatki.items.6.count"),
      },
      {
        id: 61,
        price: 5,
        image: "/images/menu/empty.svg",
        name: t("common.menu.dodatki.items.7.name"),
        description: t("common.menu.dodatki.items.7.description"),
        count: t("common.menu.dodatki.items.7.count"),
      },
    ],
  },
];